### ISSUE TITLE
select clarification

### ISSUE THREAD

**Issue by remicollet** [krakjoe/parallel#12]
See https://github.com/krakjoe/parallel/issues/10#issuecomment-467497561  for reproducer

Working on some tests / examples, I notice select always wait for the first task in the array to finish, while we may expect to wait for any task which finish first.

Using linked example

Output:
```
+ 0 started
+ 1 started
+ 2 started
+ 0 ended   <===== why ?
+ 3 started
+ 1 ended
+ 4 started
Done

+ 2 ended
+ 3 ended
+ 4 ended
```

Expected:
```
+ 0 started
+ 1 started
+ 2 started
+ 2 ended
+ 3 started
+ 1 ended
+ 4 started
Done

+ 3 ended
+ 4 ended
+ 0 ended <=== Task 0 is the longer, so should terminate last.
```

Can you please confirm if this is expected, or an issue ?

**Comment by krakjoe** [comment]
> I notice select always wait for the first task in the array to finish

That's correct/expected, more precisely, the only item in `$resolved` will always be the first task that resolved without error, whether using blocking or timeout. It seems a bit strange to accept an array for `$resolved` at all, since it will only ever have one `Future`, however, it makes the loop body a bit simpler, if everything  you are working with is an array, I think.

The timed api may be a better use case for waiting for whatever finishes (without error/timeout).

**Comment by remicollet** [comment]
> the only item in $resolved

OK for **Resolved**

> will always be the first task that resolved without error

Excepted it is always the first task in **Resolving**, despite in example, this is the longer (`sleep(3`)), and should be the last to finish.
