### ISSUE TITLE
Feature request: Channel::closed()

### ISSUE THREAD

**Issue by flavioheleno** [krakjoe/parallel#136]
Per the documentation, if you call `Channel::send()` ([reference](https://www.php.net/manual/en/parallel-channel.send.php)) or `Channel::recv()` ([reference](https://www.php.net/manual/en/parallel-channel.recv.php)) on a closed channel, a `\parallel\Channel\Error\Closed` will be thrown.

Note that the same happens when you call `Channel::close()` ([reference](https://www.php.net/manual/en/parallel-channel.close.php)).

The problem is that there is no standard way to check, prior to calling send/recv/close, if the channel is closed or not.

Of course there is a workaround using a `try`/`catch` block, but that looks hack-ish.

**Comment by flavioheleno** [comment]
Hi @krakjoe / @remicollet , I know that time is probably quite short on your side, but is there anything else I should/could do for this request and its PR be reviewed?

Thank you very much in advance!

**Comment by krakjoe** [comment]
The problem is that there is no safe way to do a Channel::close - you cannot retain the mutex associated with the state of the channel in userland.

The solution is to consider it a logic error when you call any of those methods on a closed channel, and revise your code: Your code should know for certain whether a channel is available or not.
