### ISSUE TITLE
Code runs slower in thread than in forked process

### ISSUE THREAD

**Issue by marcusjhdon** [krakjoe/parallel#210]
Hi

I've recently converted a CLI application that previously forked multiple processes to be multi-threaded instead. It works fine, but I was surprised to discover it takes around 40% longer to complete using threads than it did with separate processes.

You can test this yourself with the scripts attached. On my test machine (an Intel i7 laptop with 8 cores and 16GB ram), the testThreads.php script averages 10 secs to run, while the testProcesses.php script averages 5.9 secs.

I appreciate you might not consider this a bug as such, but it's certainly a disincentive to use parallel - which is a shame because otherwise it's great!

Thanks

Marcus
[ProcessManager.php.pdf](https://github.com/krakjoe/parallel/files/6880639/ProcessManager.php.pdf)
[ThreadManager.php.pdf](https://github.com/krakjoe/parallel/files/6880658/ThreadManager.php.pdf)
[testProcesses.php.pdf](https://github.com/krakjoe/parallel/files/6880659/testProcesses.php.pdf)
[testThreads.php.pdf](https://github.com/krakjoe/parallel/files/6880660/testThreads.php.pdf)

**Comment by FelipeAzambuja** [comment]
@marcusjhdon ProcessManager have licence ? I want to create a package with your code with some modifications.

I have tested your code and it is really good.

**Comment by marcusjhdon** [comment]
Hi @FelipeAzambuja 

You're welcome to use the code, but I recommend you test it very thoroughly before using in production. It's based on something I wrote many years ago, but was simplified for the sake of this demo and hasn't been properly tested.

Marcus

**Comment by StupidSimplePHP** [comment]
I just realised the sample code attached is only checking for available threads/processes once every second. Please change the interval parameter to 0.1s (100000) or less while testing. The problem still occurs.

**Comment by marcusjhdon** [comment]
I just realised the sample code I provided is only checking for available threads/processes once every second. Please change the interval parameter to 0.1s (100000) or less while testing. The problem still occurs.

**Comment by ClosetGeek-Git** [comment]
Just a shot in the dark, but the process version is using pipes to send it's value back to the parent. This is atomic on modern Linux as long as the value being sent is less then 1024 bytes. Not sure yet sure how parallel is internally moving data back into the main thread but I would imagine that it may be serializing things. PHP data types can be complicated and variable so I would imagine they are using a blocking queue or shared memory with some sort of synchronization such as a mutex.

Edit next day: I misread your code and see now your not communicating with the parent. I think the OP has a good question, regardless of what he's specificly trying to do, I'm wondering where he might be experiencing an issue when you consider nothing is being shared. I'm wracking my brain wondering if it can somehow be something native within the open_ssl library, for example if ```openssl_random_pseudo_bytes()``` could possibly maintain a common seed between threads to help prevent collision between the numbers it generates.  Resources created during MINIT can be shared between threads if I'm not mistaken, isn't that how TSRM works?

**Comment by ClosetGeek-Git** [comment]
@krakjoe I think this might be a worthwhile bug to dig into because it may pertain to how parallel _could_ possibly expose bugs in other 3rd party or even core extensions for PHP. They simply aren't used to being ran in a  multi-thread environment keeping long-executing code within individual threads, so I'm sure there's little focus to possible bugs in such use cases. I can see this being a step towards other extensions becoming more thread friendly. Frankly I would love to see the effects of running **all** php tests a few thousand times within parallel or a similar SAPI. A lot can be learned. I think I'm going to spend the day fiddling with the idea just to see what I see.

**Comment by TheTechsTech** [comment]
This might be a good short read:
Shared Memory Programming with Pthreads - https://sites.cs.ucsb.edu/~tyang/class/240a17/slides/pthreads.pdf

The problem I see, that seems in **contradiction** about the premise of CSP - [message passing over channels](https://www.php.net/manual/en/philosophy.parallel.php), this library's design to maintain the `global` usage.

There are a few tests making sure of this, as in this one: https://github.com/krakjoe/parallel/blob/c4415c5994cc8c83514d6d7664f16d9789bd670b/tests/base/002.phpt#L14

**Comment by ClosetGeek-Git** [comment]
The issue is openssl itself, not the openssl extension. The threadsafe library uses locks for multiple structures. I haven't been able to find the Linux code but the windows code uses ```WaitForSingleObject``` which typically takes multiple microseconds. Might not sound like much but your code is calling openssl_random_pseudo_bytes 6,400,000 times between all 8 threads, so I can see that adding multiple seconds of time overhead.

[edit]
Just in case I wasn't clear for those who are researching parallel for possible issues, this isn't a parallel issue or an issue with PHP thread handling. 

http://konradzemek.com/2015/08/16/asio-ssl-and-scalability/

**Comment by ClosetGeek-Git** [comment]
Maybe try something like https://gist.github.com/farhadi/2185197#file-rc4-php if your just trying to do side-by-side processing benchmarks. It's a pure PHP version of RC4 encryption.

**Comment by krakjoe** [comment]
This isn't caused by php or parallel, you would have to be a real expert in openssl to determine if there is anything you can do; there likely isn't.

If you are absolutely sure I'm wrong, please open a new ticket, and please include reproducing code that is not embedded in pdf documents :)

**Comment by marcusjhdon** [comment]
Openssl was just chosen at random as a suitable load-intensive operation to demonstrate the problem. You can replace it with anything you like to witness the same problem.

PS I tried embedding the code, but it didn't seem to preserve indentation correctly, hence the PDF files.
