### ISSUE TITLE
Does Parallel copy classes for every new thread created ?

### ISSUE THREAD

**Issue by polyphia** [krakjoe/parallel#220]
Can someone please confirm if parallel copies classes everytime a new thread is created, similarly to what pthread does ?

I have detected a bottleneck in pthreads causing a delay in each thread submitted because of this. Opcache would fix this if it worked properly , but it never does . 

Trying to understand if Parallel also copies classes everytime a new thread is submitted .

**Comment by dotfry** [comment]
Yes.

**Comment by cmb69** [comment]
This doesn't appear to be particularly related to parallel or pthreads, but is rather a general property of thread-safe PHP builds (ZTS). Without OPcache, the classes are stored in thread-local storage, so each thread has its own copy. But even with OPcache, starting a ZTS thread has some overhead, since module globals need to be initialized, classes may need to be linked, etc.

Anyhow, I think this ticket can be closed.

**Comment by sj-i** [comment]
Note that preloading can also be used even in the CLI, in which case the linked code will be shared by each thread.

**Comment by krakjoe** [comment]
parallel does not copy classes, they have to be made available by opcache or bootstrap.
