### ISSUE TITLE
Parallel and JIT

### ISSUE THREAD

**Issue by GajowyJ** [krakjoe/parallel#265]
I wonder how JIT deals with parallel? 
Does JIT compile the $process function (and everything called inside) every time it is run(), or it can be compiled only once and then the compiled code is reused?

```
$run = new Runtime();
$fut = $run->run( $proces );

```

```
use parallel\{Runtime,Future};
$proces = function( )
{
	include('MyLibrary.inc');
	return MyFunctionDefiniedInIncludedFile();
};

```

**Comment by realFlowControl** [comment]
Hey there 👋 

the file is only compiled once, if you have the OPcache enabled. The JIT is not involved in file compilation.

```php
<?php

use parallel\Runtime;
$process = function(){
    include("empty.php");
    return empty();
};

$run = (new Runtime())->run($process);
$run = (new Runtime())->run($process);
$run = (new Runtime())->run($process);
$run = (new Runtime())->run($process);
```

This case will start four threads, the first one will compile and store in OPcache, the other three will use the opcodes found in OPcache. You can make this visible by running this script with [`ext-include-logger`](https://github.com/realFlowControl/ext-include-logger) which only shows one compilation for `empty.php`.

But here is a catch:

```php
<?php

use parallel\Runtime;
$process = function(){
    include("empty.php");
    return empty();
};

$run = new Runtime();
$run->run($process);
$run->run($process);
$run->run($process);
$run->run($process);
```

This will span one thread (one Runtime) and execute the closure one after the other. Starting with the second invocation this will fail with a
```
Fatal error: Cannot redeclare empty() (previously declared in ...)
```
(assuming the `empty.php` defines the `empty()` function).
This is because it is reusing the same thread to run that closure. So better use `include_once()` to be safe or handle that case with a `function_exists()` call in the `empty.php`.

Note: This is nothing special or related to parallel, this is just as if you'd include the same file twice in any other PHP script.

Hope I could help
