### ISSUE TITLE
echo in Runtime function writes to header field

### ISSUE THREAD

**Issue by dukedrake** [krakjoe/parallel#275]
PHP Version: 8.2.4 FPM
Parallel Version: 1.2.1

I'm trying my first steps with the parallel extension. While the first example on https://www.php.net/manual/en/class.parallel-future.php works, the echo in the second example https://www.php.net/manual/en/class.parallel-future.php#example-3407 results in an error:
AH02429: Response header name 'in child .................................................. leaving childX-Powered-By' contains invalid characters, aborting request

So, the output is prepended to the header-field "X-Powered-By" ...? Why? How???? xD

Please advice, thank you =)

**Comment by harryqt** [comment]
FPM? parallel only works on CLI.

**Comment by dukedrake** [comment]
@Dibbyo456  Sorry but this is not helpful at all..... where does it say that the library only works with CLI?

**Comment by harryqt** [comment]
Parallel depens on [pthread](https://github.com/krakjoe/parallel/blob/develop/INSTALL.md) which only works in CLI. See #35 for more info.

**Comment by 5lava** [comment]
The example doesn't work in FPM because the output from the child thread is sent back to the web server before the main thread sends HTTP response headers. To fix that, you can disable output buffering entirely in php.ini, or close output buffers in the main thread before the child thread produces output for the response body. Consider adding the following code before you call `$runtime->run()`:

```php
while ( ob_get_status() ) {
  ob_end_flush();
}
```

**Comment by realFlowControl** [comment]
Hey @dukedrake,

as @harryqt mentioned, please go ahead and read https://github.com/krakjoe/parallel/issues/35#issuecomment-492125610

This does not mean, that it is impossible to use `ext-parallel` in PHP-FPM, but you need to be aware of the side effects this comes with.
