### ISSUE TITLE
Behavioural inconsistency with normal classes on wrong argument types

### ISSUE THREAD

**Issue by dktapps** [krakjoe/parallel#30]
Normal typehinted methods will throw `\TypeError` when wrong types are passed to them. parallel is currently throwing its own baked exception, which seems strange to me. It seems like it would be less work to use `ZEND_PARSE_PARAMS_THROW` instead? Am I missing some obvious reason why this is different?

**Comment by krakjoe** [comment]
The whole arginfo and parsing parameters thing is a bit of a mess internally ... we can't use throw because in some cases we need to set the state of an object when the wrong arguments are used to avoid deadlocks. We can't use arginfo because when you use arginfo for internal functions it is used to verify types - PHP_METHOD will never be entered if that verification does not pass.

On top of the requirements we have, the internals API's have inconsistencies that can only be worked around by what we are doing now ...

In the end it quite suits us: Just as we have to set the internal state of some objects upon a called failure, user land code may need to travel a specific path to avoid deadlocks in userland, that is why \parallel\Error\InvalidArguments doesn't derive from TypeError, so that you must specifically write a catch block for those errors and do whatever management of state you may have ...

With the introduction of channels, the number of ways to make your code deadlock has increased about a billion fold (number pulled from air), that's why I've gone down the route of introducing specialised exceptions even though I don't really like that in normal code. They allow you to very finely control exceptional states, and hopefully avoid deadlocks or some of them ...

**Comment by krakjoe** [comment]
I decided I didn't like my excuses for the difference, and I'm not in the mood to take any of my nonsense, so I fixed it ...

We're now unified with internals with arginfo everywhere and TypeError for all bad calls ...

It's still the case that you might have state to manage, so specialised exceptions make sense for the reasons I gave, but it doesn't make sense to diverge from internals in the case of parameter parsing.

**Comment by krakjoe** [comment]
Fixed in cdc4f5d1a75e13d3562b7f2e8530e2e35d5b66f6

**Comment by dktapps** [comment]
Yup, fully agreed. Thanks.
