### ISSUE TITLE
 I found that running nginx in non cli mode on a web browser did not achieve the expected results, but if executed in cli mode, it did achieve the expected results.

### ISSUE THREAD

**Issue by jasonccs** [krakjoe/parallel#310]
![image](https://github.com/krakjoe/parallel/assets/17975766/5c7d33aa-d786-4d69-ae47-1766deac636a)

this code 

$runtime = new \parallel\Runtime();

$future = $runtime->run(function(){
    for ($i = 0; $i < 500; $i++)
        echo "*";

    return "easy";
});

for ($i = 0; $i < 500; $i++) {
    echo ".";
}

printf("\nUsing \\parallel\\Runtime is %s\n", $future->value());

I found that running nginx in non cli mode on a web browser did not achieve the expected results, but if executed in cli mode, it did achieve the expected results.

**Comment by realFlowControl** [comment]
Hey @jasonccs 👋 

thanks for trying out `parallel`.
I tried using the content from https://github.com/krakjoe/parallel?tab=readme-ov-file#hello-world with `php -S 127.0.0.1:8080 -t ./` and then sending HTTP requests to that URL and it worked. The thing is, you wont see a perfect `.*.*.*.*.*.*.*...`-pattern, but this is just due to race conditions in the code (it is not syncing, just echoing, so whoever comes first comes first).
On another note: I'd advice to not echo out in "worker threads". `parallel` makes sure that only one thread can echo at a time by using a mutex, but still there might be side effects in Apache/php-fpm/FrankenPHP/... (all request based SAPIs) that might give you a hard time. That said: it should work 😉

**Comment by realFlowControl** [comment]
This is btw.: the output I get:
```
**...*******...**......****************.......******.....................*********************************************..........******...........************.......**************......******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************.......................................................................................................................................................................................................................................................................................................................................................................................................................................... Using \parallel\Runtime is easy
```
