### ISSUE TITLE
Usefulness of channel naming

### ISSUE THREAD

**Issue by dktapps** [krakjoe/parallel#48]
It seems to me that channel naming is no longer useful, thanks to the ability to pass channels directly between threads with the newly implemented object support. I'm now finding myself needing ways to uniquely identify channels, which is starting to involve things like randomly generated UUIDs.

It seems to me that channel names could be dropped, along with `Channel::make()` and `Channel::open()`.

**Comment by krakjoe** [comment]
> I'm now finding myself needing ways to uniquely identify channels, which is starting to involve things like randomly generated UUIDs.

I had thought about dropping make/open and the ability to reference a channel by name. My thinking is this:

  - They are no more difficult to name than the variables which represent them
  - It offers more possibilities of integration, if you document "do X by sending Y to channel Z", all the integrator needs is the name of a channel, it doesn't necessarily need to be passed the dependency ... in one sense this is simpler, but in another it's a bit like magic super globals ...
  - Having one way to do thing is simpler than having two, make/open is a known idiom, that we already implemented, removing it seems to be rather disruptive (disruption doesn't mean bad).

Having said all of that, I know that my first point isn't really true in the real world, although I didn't imagine anyone would have to be going to the lengths of generating random names, that's really horrible ...

I'm very open to switching the API over to conventional constructor based API, can I hear some more feedback from anyone else ?

Note that this change would go further than just dropping the name from channel, it would mean changing the events api (to be simpler actually), and event vo also (again, simpler) ... while the user facing changes would make events a little simpler, it's more complicated internally if objects don't have names ... I don't really have a solution for this right at this moment ...

**Comment by dktapps** [comment]
As far as your first point goes, in a complex program it starts to become necessary to think about channel name collisions so that you don't open the wrong thing by mistake. Channel names are truly global, so this means libraries have to take extra care to declare appropriate identifiers to avoid collisions -> reinventing namespaces. In my opinion this is an unnecessary burden.

My personal thought would be that they'd have some kind of internal generated ID that parallel itself can use. Perhaps some kind of counter like object ID would be sufficient.

Right now I have no use for channel naming because I just pass the object references directly as closure parameters. The channel name is just an inconvenience at this point.
It also creates complications for the code opening an existing channel, since it doesn't know if the name it's trying to use to open a channel actually exists, but if it receives a `Channel` as parameter, that problem disappears.
```php
$chan = Channel::make("idc");
\parallel\run(function(Channel $chan){
	$chan->send("hi");
}, [$chan]);

echo $chan->recv() . PHP_EOL;
```
```php
$name = "idc";
$chan = Channel::make($name);
\parallel\run(function(string $name){
	try{
		$chan = Channel::open($name);
	}catch(Channel\Error\Existence $e){
		assert(false, "no such channel");
	}
	$chan->send("hi");
}, [$name]);
echo $chan->recv() . PHP_EOL;
```

**Comment by krakjoe** [comment]
Anyone else got any input here ?

**Comment by WyriHaximus** [comment]
> Anyone else got any input here ?

To be honest I'm using prefixed randomly generated channel names anyway so I don't really have a use case for channel names anyway. Both measures are to ensure we get a unique channel name to avoid collisions.

**Comment by krakjoe** [comment]
Ok, so channel names are terrible and we should drop them ... ACK ...

I'll start working on that, I guess it will form the basis of v1.1 ...

**Comment by dotfry** [comment]
Sometimes it may be useful, may be make name optional?

**Comment by krakjoe** [comment]
If we keep using names internally, and have them as optional for userland, it moves the problem of generating these random names from userland to internals. I don't much like the thought of that ...

In addition, I think it better if there's one clear way to use Channels, so think it best to just drop the names.

In those cases where it might be useful to name your channels, you could still do that in userland, and the fact that you have to generate names isn't a problem in that case.

**Comment by dotfry** [comment]
As I see in the code, the name is used as the key of the hash table, whether this will affect the performance?

When removing this, is it possible to add a method such as `Channel::setName`?

**Comment by krakjoe** [comment]
Work on this has been done in channels-without-names branch: 0d509532c7be10baebe5eede3c86d3d5b488ad63

I've not done a lot of testing beyond making sure the tests pass ...

I think I have to drop Input, it's not safe to use the addressof the zend_object as a key in a hashtable if I can't be sure the address will not be reused, and because the input hash doesn't keep a reference to the object, it may be reused - it might end up writing the wrong input to the wrong channel in that case.

So, I'm not done yet ...

> As I see in the code, the name is used as the key of the hash table, whether this will affect the performance?

Using long indexes is faster than using string keys ...

> When removing this, is it possible to add a method such as Channel::setName?

I don't want to add unnecessary methods, if the name is not used internally then it doesn't really make sense to add a setName method ...

**Comment by dktapps** [comment]
@krakjoe what about an internal incrementing channel ID counter instead of names?

**Comment by krakjoe** [comment]
I'm not sure ... I'm actually not sure about this approach as I go to sleep
tonight. The problem is you now cannot identify channels, they have
different handles in every thread, debugging this is hard.

I need more thinking time ...

**Comment by krakjoe** [comment]
There are things I like about this approach:

  - we no longer have to maintain a list of channels
  - many threads may create channels concurrently (not possible before because of the list of channels)
  - there is much less boilerplate
  - it shrinks the Channel API
  - it shrinks the Events API
  - it shrinks the Event VO
  - it means less string comparisons in userland

There are things I don't like about this approach:

  - debugging is actually impossible without a way to identify a channel across threads
  - not being able to open a channel by name actually makes code more complicated - lots of functions are going to have prototypes like function(Channel $c, Channel $d, Channel $e)
  - I really don't see a difference between naming a Channel like $c and naming it like "c" and having the same variable name
  - it's changed *a lot* of APIs
  - I can't confidently commit this to develop because I can't confidently debug some complex scripts I have been using for testing (like that crawler thing), and I can't run amp-parallel's tests, which I've also been using for testing because they seem to show up bugs more than my test suite (down to use of generators, killing, timeouts etc but I can't reproduce simply).
  - it's going to make a mess in docs ...

I'm not sure what is the best way forward ...

**Comment by krakjoe** [comment]
An internally incrementing counter sounds reasonable, however, we would either have to lock that counter, or use atomics to increment it, the former introduces exclusion that makes the second thing I like about it moot. The latter is something I have thus far tried to avoid, while atomics are standard in C++, they are not standard in C, and while there is an accepted convention for compilers I'm familiar with (__atomic* apis), I'm unfamiliar with the interlocking APIs for windows, although I've read about them and seen them being used in code I didn't write.

Another approach which is used internally to name closures, is to use the file and opline address to generate a name, while you only see {closure} the name is actually {closure}\0/opt/src/whatever.php0xXXXXXXXX, so far this has caused internals no issues with closures, so I guess we can reuse that strategy (without the null so you can see the generated name while debugging).

Having named and unnamed channels is something I want to avoid, we need to choose a way and make it reasonable, I don't want to be a box of everything ...

The wide reaching changes to API's I'm not really pleased about even though they seem positive, I don't like the idea of making a mess in the manual already and deleting pages is frowned upon by the manual editor.

Having said all these words, I'm still not sure we should do this, I need some convincing, and or some input from other people ...

**Comment by dotfry** [comment]
That looks good, but it is a pity that the functionality to get the channel using `Channel::open()` is removed.

**Comment by krakjoe** [comment]
I got another idea ... what if we kept the named constructor (Channel::make) for named channels, and used the normal constructor (Channel::__construct) for un-named channels, which we give a name, this would allow the rest of the API to remain unchanged, as well as reflection (arginfo) to be sensible for make() and __construct() (merging un-named channels into the named constructor means strange arginfo for make method), and still allow you to create "anonymous" channels ?

> Having named and unnamed channels is something I want to avoid

It still means all channels are named internally, it's just *you* don't have to give them a name ...

**Comment by krakjoe** [comment]
I decided to go with that ... so we have "anonymous" channel support in Channel::__construct and named channels remain unchanged.

**Comment by dktapps** [comment]
I feel like the choice for names could be a problem ... what about if the same function is creating channels in multiple calls?

**Comment by krakjoe** [comment]
Hm, that's true ... so we won't use the opline ... so that new Channel will never fail ...

**Comment by krakjoe** [comment]
Better ? (we also have useful info in the name now, the scope that created it and line number, the opline remains for debugging purposes) ...

**Comment by dktapps** [comment]
that looks better yes :+1:

**Comment by krakjoe** [comment]
So anonymous channels are named are like `scope#lineno@address[idc]" ... where scope is the filename for files and closures (because closures don't have human readable names), "class::function" for methods, and "function" for functions ... and idc (ulong) is incremented for every anonymous channel ...

**Comment by dktapps** [comment]
it turns out that explicit names may be useful for static initialisation.

```php
class Test{

    private static $chan = null;

    public static function getChan() : Channel{
        static $name = __FILE__ . "#" . __LINE__;
        if(self::$chan === null){
            try{
                self::$chan = Channel::make($name);
            }catch(\parallel\Channel\Error\Existence $e){
                self::$chan = Channel::open($name);
            }
        }
        return self::$chan;
    }
}
```
Perhaps it might be useful to have something similar for `\parallel\Sync`.
