### ISSUE TITLE
Check whether future has a value

### ISSUE THREAD

**Issue by ghost** [krakjoe/parallel#5]
Is there a way or could you add a method to check whether the Future has a value (i.e. is done or errored)? Currently you can only try to get the value and it will block until it has the value. For an asynchronous environment this is highly inefficient and lowers throughput.

**Comment by krakjoe** [comment]
> Is there a way or could you add a method to check whether the Future has a value (i.e. is done or errored)?

It would look something like:

  1) lock future
  2) save state
  3) unlock future
  4) return state to userland

This is quite messy, as I'm sure you see ... moreover after 3, and before 5 (your next userland instruction), the state may have changed. In order to use that kind of API, you would have to have a busy waiting loop, and this is really horrible. 

There's a possibility to add a timeout parameter to `value()`, which set to 0, would allow you to do a kind of non-blocking fetch, but this again would require a busy loop, and I'm not sure how well this is going to fit with other bit of the API I'm currently designing. I'm not sure if what you want is some sort of `select()` to work on a set values, and I'm not sure if that best fits in the current Future API, or the Channel API that is coming.

I'll have a solution at some point, but I'm reluctant to just make the change, I need to think about it for a while, consider the implications, and discuss it with other internals folks.

I'm very glad you decided to look at parallel anyway ... let's not be hasty, there's plenty of time to get it right :)

**Comment by ghost** [comment]
> 
> 
> > Is there a way or could you add a method to check whether the Future has a value (i.e. is done or errored)?
> 
> It would look something like:
> 
>     1. lock future
> 
>     2. save state
> 
>     3. unlock future
> 
>     4. return state to userland
> 
> 
> This is quite messy, as I'm sure you see ... moreover after 3, and before 5 (your next userland instruction), the state may have changed. In order to use that kind of API, you would have to have a busy waiting loop, and this is really horrible.
> 
> There's a possibility to add a timeout parameter to `value()`, which set to 0, would allow you to do a kind of non-blocking fetch, but this again would require a busy loop, and I'm not sure how well this is going to fit with other bit of the API I'm currently designing. I'm not sure if what you want is some sort of `select()` to work on a set values, and I'm not sure if that best fits in the current Future API, or the Channel API that is coming.

Some sort of stream that could be used with stream select would be a good solution to me, but if some other reasonable solution with the Channel API can be achieved, it would be fine to me too (as long as you could stream select on it?).

Something of this can probably be efficiently achieved with the Channel API if the Channel API can be used with a select. Then we would just have to wrap the closure into a closure which would send the necessary notification "message" (probably some sort of try-finally block). Although I think this could be efficienter on the C level. :)


> I'll have a solution at some point, but I'm reluctant to just make the change, I need to think about it for a while, consider the implications, and discuss it with other internals folks.

Don't worry, take the time you need (as long as it's not years :)).

> I'm very glad you decided to look at parallel anyway ... let's not be hasty, there's plenty of time to get it right :)

Parallel can be used for other things I am doing (just simple parallel computation), just not for that one project I am using pthreads widely for - and more than just simple parallel computation. :)

**Comment by krakjoe** [comment]
> Some sort of stream that could be used with stream select would be a good solution to me, but if some other reasonable solution with the Channel API can be achieved, it would be fine to me too (as long as you could stream select on it?).

Well it would be more like Channel::select, or Future::select, but analogous to and recognisably a `select` call.

It's just been pointed out to me that the lock is superfluous if you're only checking the state, but the thing that concerns me, and that `select` would avoid, is busy waiting loops in userland.

**Comment by ghost** [comment]
Busy waiting loops isn't really a concern if I can select it. But it's a concern if I can't use an userland event loop for it. A `stream` resource would allow me to integrate it into an userland event loop (e.g. ReactPHP stream select event loop).

But if I can't get a resource to select it, I'd do an alternative timer implementation to get the Future state and compare (which I've been using if `ext-sockets` is not installed/enabled for a pthreads pool too).

**Comment by krakjoe** [comment]
Done, see updated readme ...
