### ISSUE TITLE
[parallel\Runtime\Error\Bootstrap] bootstrapping failed

### ISSUE THREAD

**Issue by feamsr00** [krakjoe/parallel#72]
Forgive but I'm getting exasperated here without documentation.

What exactly are the conditions that would cause bootstrapping to fail?

(Is is possible to have ether better exception messages or a known list of failure conditions?)

**Comment by krakjoe** [comment]
Bootstrapping will fail if:

  - the file cannot be opened: https://github.com/krakjoe/parallel/blob/develop/tests/base/029.phpt
  - the file cannot be compiled: https://github.com/krakjoe/parallel/blob/develop/tests/base/034.phpt
  - the file cannot be executed (threw uncaught exception): https://github.com/krakjoe/parallel/blob/develop/tests/base/033.phpt

I somehow (wrongly) thought it obvious that it would have roughly the same failure conditions as a call to include(), but two things have happened (or failed to happen) - 

  - When I converted the documentation from stub in readme into phpdoc, I removed the definition of what bootstrapping means (included upon construction, before anything is run).
  - When I added the ability to save an exception from any context and restore it in any context, I failed to update the bootstrap routine to do this. So that you may (configuration allowing) get a warning if the file cannot be found, but exceptions (from compile/execute) are hidden.

This can be improved ...

**Comment by feamsr00** [comment]
Thanks for sharing that! That makes a lot more sense now. If I understand correctly that bootstrapping is just a localized use of `include`, I would agree that it would be simplest for it to simply emit the same failure messages that `include` could.

Note: Since parallel\Runtime is final, might I suggest adding a setBootstapRoutine? There are scenarios where a "boot file" isn't the most appropriate mechanism. (Even with autoloading. My use case has a generated classmap already loaded to memory)

**Comment by dktapps** [comment]
> might I suggest adding a setBootstapRoutine

you can just submit a closure to `run()` directly after creating the runtime.

**Comment by feamsr00** [comment]
Thanks for that idea @dktapps . Now, I'm curious though. If I pass a "stub" file to the `Runtime` constructor (say... to prepare the env for a thread about to launch), is there any way to "communicate" with it? Is the best way to do that to use a "named channel"? (while naming seems like a semantic hassle, I don't think I see anyway around that.) In this way could you have an "inbox" of data to access by the "stub" before ::run()'s callable (the "thread") is executed? This would keep threads more specialized and naive as to their own initialization.

**Comment by Tuckbros** [comment]
I leave it here because I feel it is related. As you can't declare a class in a function/closure, you have to create a bootstrap file for the `class` declaration you need in your worker, however simple it is, and you have to make sure you don't forget to 
`use \parallel\{Runtime, Future, Channel, Events};`
if you plan to make it work with channel (and other if needed).
