### ISSUE TITLE
select() timedout vs resolving unclear usage

### ISSUE THREAD

**Issue by dktapps** [krakjoe/parallel#9]
As far as I can see in the code these arrays will always have the same contents. Why are they both present? Am I missing some crucial difference?

**Comment by krakjoe** [comment]
I'm very well aware that this API needs more than docblock comments, I'm planning to start the project of documentation in the manual when PECL is started .... I really don't want to clutter the readme here with lots and lots of examples ... so that's the first thing to say ...

`$resolving` is your input array of Future objects, which is taken by reference so that it may be updated for subsequent invocations.

`$timedout` will be filled with Future objects from `$resolving` which timedout while waiting for a value.

Future objects that timedout are not resolved, so are not removed from the `$resolving` set of objects so that subsequent iterations may attempt resolution again ...

A little example should help:

```php
<?php
$i = 0;
$workers = [];

while ($i++ < 5) {
	$workers[$i] = new \parallel\Runtime();
}

$i = 0;
$futures = [];

while ($i++ < 5) {
	$futures[$i] = $workers[$i]->run(function($sleep){
		sleep($sleep);
		
		return $sleep;
	}, [$i]);
}

$resolved = [];
$errored  = [];
$timedout = [];

$start      = microtime(true);
$iteration  = 0;

while (\parallel\Future::select($futures, $resolved, $errored, $timedout, 1000000)) {
	printf(
		"Iteration: %d [%.2f] Resolved: %d, Timedout: %d\n", 
		++$iteration,		
		microtime(true) - $start, 
		count($resolved), 
		count($timedout));
}
?>
```

Will output something like (I'll annotate the log)

```
Iteration: 1 [1.00] Resolved: 0, Timedout: 5
Iteration: 2 [1.00] Resolved: 1, Timedout: 0
Iteration: 3 [2.00] Resolved: 0, Timedout: 4
Iteration: 4 [2.00] Resolved: 1, Timedout: 0
Iteration: 5 [3.00] Resolved: 0, Timedout: 3
Iteration: 6 [3.00] Resolved: 1, Timedout: 0
Iteration: 7 [4.00] Resolved: 0, Timedout: 2
Iteration: 8 [4.00] Resolved: 1, Timedout: 0
Iteration: 9 [5.00] Resolved: 1, Timedout: 0
```

  1) nothing is ready, everything timed out, so all Future objects are in `$timedout`, the full one second timeout was reached
  2) the first Future resolved and there was (practically) no blocking from select, `$timedout` is empty because select returned on the first resolution, and the resolved Future was removed from `$resolving` set
  3) nothing more is ready, so all 4 objects in `$resolving` timed out, `$timedout` contains all 4 objects, the full one second timeout was reached
  4) the second Future resolved, and again practically without blocking select returned, again `$timedout` is empty, resolved Future was removed from `$resolving` set

I think I don't need to type out the rest of the annotation for you to understand what's going on :)

**Comment by dktapps** [comment]
I see. There is indeed a subtle difference that I didn't spot. Nonetheless it seems to me that the usefulness of `$timedout` is very small.

**Comment by krakjoe** [comment]
You may at a certain point during loop decide that some Future is never going to resolve, and so remove it from `$resolving` yourself. There's no way to make that decision for you, and it's useful to know the difference between errored and timedout, which is why timedout is not inserted into errored.

**Comment by dktapps** [comment]
That makes sense. Thanks for explaining.

**Comment by krakjoe** [comment]
Very welcome :)
