### ISSUE TITLE
Big array_search with parallel

### ISSUE THREAD

**Issue by cabelito** [krakjoe/parallel#92]
Hello,
I am pretty new to threading with PHP but overall I have understandings of what should be done. I have tried a lot of ways to optimize my scripts using parallel but no success.
What I am trying to accomplish is the following situation:
I am selecting array from MySQL database ( 1,2 Milions of records ) into PHP array and then trying to find matching number ( array is made of numbers ) with array_search. with single thread. Currently I have i5 4570T with Linux and PHP 7.3.9 with ZTS compiled
Array made of 1.2 Million of records ( each record is 15 numbers ) is checked for around 700-900 ms . I am trying to optimize my script to be threaded and to get better performance. Is this doable with parallel ? Any Help will be appreciated .
I have tried to submit big array to parallel function but it takes more time to submit this big array than to calculate the result ( about 1300 ms to get to the function and then additional time for processing the array ) so this way is NO GO. ? Any other options ? I know I cannot share memory/array between threads ?

Thanks in advance to everyone

**Comment by Tuckbros** [comment]
You can find ideas in there : [https://gist.github.com/krakjoe/0ee02b887288720d9b785c9f947f3a0a](https://gist.github.com/krakjoe/0ee02b887288720d9b785c9f947f3a0a) it is a quite complete example of what you can do with parallel. The documentation explains somewhere that data are copied from the main thread to the others. I suppose it is what costs a lot of time and make it worse than direct processing. Are you slicing your big array to make parallel processing ?  But this question would find a better place in stackoverflow with your current code rather than here as an issue.

**Comment by ghost** [comment]
Copying data is expensive, and has to be done due to share nothing architecture. What you need or want to do is slice the array and submit each chunk to a worker for processing.

**Comment by krakjoe** [comment]
Sorry, this is outside of the scope of issues.
